# Coding Your Own Linear Regression Model

One task that you will almost certainly be required to do other data science courses (especially if you are a MIDS student) is to write up some of your statistical / machine learning models from scratch. This can be a very valuable exercise, as it ensures that you understand what is actually going on behind the scenes of the models you use ever day, and that you don't just think of them as "black boxes". 

To get a little practice doing this, today you will be coding up your own linear regression model! 

(If you are using this site but aren't actually in this class, you are welcome to skip this exercise if you'd like -- this is more about practicing Python in anticipation of the requirements of other courses than developing your applied data science skills.) 

There are, broadly speaking, two approaches you can take to coding up your own model: 

1. you can write the model by defining a new function, or 
2. you can write the model by defining a new class with associated methods (making a model that works the way a model works in `scikit-learn`). 

Whether you do 1 or 2 is very much a matter of choice and style. Approach one, for example, is more consistent with what is called a *functional* style of programming, while approach two is more consistent with an *object-oriented* style of programming. Python can readily support both approaches, so either would work fine. 

In these exercises, however, I will ask you to use approach number 2 as this *tends* to be the more difficult approach, and so practicing approach 2 will be extra useful in preparing you for other classes (HA! Pun...). In particular, our goal is to implement a linear regression model that has the same "initialize-fit-predict-score" API (application programming interface -- a fancy name for the methods a class supports) as `scikit-learn` models. That means your model should be able to do all of the following:

1. **Initialize** a new model. 
2. **Fit** a linear model when given a numpy vector (`y`) and a numpy matrix (`X`) with the syntax `my_model.fit(X, y)`. 
3. **Predict** values when given a new `numpy` matrix (`X_test`) with the syntax `my_model.predict(X_test)`. 
4. Return the **model coefficients** through the property `my_model.coefficients` (not quite what is used in `sklearn`, but let's use that interface). 

Also, bear in mind that throughout these exercises, we'll be working in `numpy` instead of `pandas`, just as we do in `scikit-learn`. So assume that before using your model, your user has already converted their data from `pandas` into `numpy` arrays. 

In [216]:
import pandas as pd
import numpy as np

pd.set_option("mode.copy_on_write", True)

**(1)** Define a new Class called `MyLinearModel` with methods for `__init__`, `fit`, `predict`, and an attribute for `coefficients`. For now, we don't need any initialization *arguments*, just an `__init__` function. 

As you get your code outline going, start by just having each method `pass`:

```python
def my_method(self):
    pass
```

This will allow your methods to run without errors (they just don't do anything). Then we can double back to each method to get them working one by one.

In [217]:
class MyLinearModel:
    def __init__(self, X, y, const=False):
        # coefficient
        self.beta = None

    def fit(self):
        pass

    def predict(self, X_test):
        pass

**(2)** Now define your `fit` method. This is the method that should actually run your linear regression. In case you've forgotten your linear algebra, remember that for linear regressions, $\beta = (X'X)^{-1}X'Y$, a fact you can see explained in detail on page four [here](https://www.stat.purdue.edu/~boli/stat512/lectures/topic3.pdf).

Note that once you have written the code to do a linear regression, you'll need to put your outputs (your coefficents) somewhere. I recommend making an attribute for your class where you can store your coefficients. 

(As a reminder: the normal multiply operator (`*`) in `numpy` implies scalar multiplication. Use `@` for matrix multiplication). 

**HINT:** Remember that linear regressions require a vector of 1s in the `X` matrix. As the package writer, you get to decide whether users are expected to provide a matrix `X` that already has a vector of 1s, or whether you expect the user to provide a matrix `X` that doesn't have a vector of 1s (in which case you will need to add a vector of 1s before you fit the model).

In [218]:
class MyLinearModel:
    def __init__(self, X, y, const=False):
        # Add constant if const=False
        if const == True:
            self.X = X
        else:
            self.X = np.insert(X, 0, 1, axis=1)
        self.y = y
        # Initialize coefficients
        self.beta = np.zeros((3, 1))

    def fit(self):
        # Coefficients computation
        XtX_inv = np.linalg.inv(self.X.T @ self.X)
        self.beta = XtX_inv @ self.X.T @ self.y

    def predict(self, X_test):
        # prediction
        y_pred = np.insert(X_test, 0, 1, axis=1) @ self.beta
        return y_pred

**(3)** As you write code, it is good to test your code as you work. With that in mind, let's create some toy data. First, create a 100 x 2 matrix where each column is normally distributed. Then create a vector `y` that is a linear combination of those two columns **plus** a vector of normally distributed noise **and** a constant term. 

In other words, we want to create data where we *know* exactly what coefficients we should see so when we test our regression, we know if the results are accurate!

In [219]:
np.random.seed(40)
X = np.random.normal(size=(100, 2))
X_test = X
noise = np.random.normal(size=(100, 1))
beta = np.array([[2], [1]])
b = 1
y = X @ beta + noise + b
X, y

(array([[-0.6075477 , -0.12613641],
        [-0.68460636,  0.92871475],
        [-1.84440103, -0.46700242],
        [ 2.29249034,  0.48881005],
        [ 0.71026699,  1.05553444],
        [ 0.0540731 ,  0.25795342],
        [ 0.58828165,  0.88524424],
        [-1.01700702, -0.13369303],
        [-0.4381855 ,  0.49344349],
        [-0.19900912, -1.27498361],
        [ 0.29349415,  0.10895031],
        [ 0.03172679,  1.27263986],
        [ 1.0714479 ,  0.41581801],
        [ 1.55067923, -0.31137892],
        [-1.37923991,  1.37140879],
        [ 0.02771165, -0.32039958],
        [-0.84617041, -0.43342892],
        [-1.3370345 ,  0.20917217],
        [-1.4243213 , -0.55347685],
        [ 0.07479864, -0.50561983],
        [ 1.05240778,  0.97140041],
        [ 0.07683154, -0.43500078],
        [ 0.5529944 ,  0.26671631],
        [ 0.00898941,  0.64110275],
        [-0.17770716,  0.69627761],
        [-1.1887251 , -0.33169686],
        [ 0.03007614, -1.10791517],
        [-0.5499249 , -2.032

**(4)** Now test whether you `fit` method generates the correct coefficients. Remember the choice you made in Question 2 about whether your package expects the users' `X` matrix to include a vector of 1s when you test!

> Our class adds the ones for the user

In [220]:
test_model = MyLinearModel(X, y)

In [221]:
test_model.beta

array([[0.],
       [0.],
       [0.]])

> Good model initialization with beta initialized at zero

In [222]:
test_model.fit()

In [223]:
test_model.beta

array([[0.94954368],
       [2.02452443],
       [1.05601786]])

> $\beta = (X'X)^{-1}X'Y$ where X is 100x3 (since we added a column of ones) should be [3x100]*[100x3] * [3x100]*[100x1] = [3x1] which is what we have. This is the beta coefficients and the intercept. We also set the coefficients in our y (apart from the noise) to be 2 and 1 so our fit is close to correct.

**(5)** Now let's make the statisticians proud, and in addition to storing the coefficients, let's store the standard errors for our estimated coefficients as another attribute. Recall that the simplest method of calculating the variance covariance matrix for $\beta$ is using the formula $\sigma^2 (X'X)^{-1}$, where $\sigma^2$ is the variance of the error terms of your regression. The standard errors for your coefficient estimates will be the diagonal values of that matrix. See page six [here](https://www.stat.purdue.edu/~boli/stat512/lectures/topic3.pdf) for a full derivation. 

In [224]:
class MyLinearModel:
    def __init__(self, X, y, const=False):
        if const == True:
            self.X = X
        else:
            self.X = np.insert(X, 0, 1, axis=1)
        self.y = y
        self.beta = np.zeros((3, 1))
        self.std_error = np.zeros((3, 1))

    def fit(self):
        # Coefficients computation
        XtX_inv = np.linalg.inv(self.X.T @ self.X)
        self.beta = XtX_inv @ self.X.T @ self.y

        # Standard error computation
        residuals = self.y - (self.X @ self.beta)
        sigma_squared = np.mean(residuals**2)
        self.std_error = np.sqrt(np.diag(sigma_squared * XtX_inv))

    def predict(self, X_test):
        y_pred = np.insert(X_test, 0, 1, axis=1) @ self.beta
        return y_pred

In [225]:
test_model = MyLinearModel(X, y)

In [226]:
test_model.fit()

In [227]:
test_model.std_error

array([0.10773008, 0.09876537, 0.1235912 ])

**(6)** Now let's also add an R-squared attribute to the model.

In [228]:
class MyLinearModel:
    def __init__(self, X, y, const=False):
        if const == True:
            self.X = X
        else:
            self.X = np.insert(X, 0, 1, axis=1)
        self.y = y
        self.beta = np.zeros((3, 1))
        self.std_error = np.zeros((3, 1))
        self.rsquared = 0

    def fit(self):
        # Coefficients computation
        XtX_inv = np.linalg.inv(self.X.T @ self.X)
        self.beta = XtX_inv @ self.X.T @ self.y

        # Standard error computation
        residuals = self.y - (self.X @ self.beta)
        sigma_squared = np.mean(residuals**2)
        self.std_error = np.sqrt(np.diag(sigma_squared * XtX_inv))

        # R-squared computation
        sum_squared_residuals = np.sum(residuals**2)
        tot_sum_squares = np.sum((self.y - np.mean(self.y)) ** 2)
        self.rsquared = 1 - (sum_squared_residuals / tot_sum_squares)

    def predict(self, X_test):
        y_pred = np.insert(X_test, 0, 1, axis=1) @ self.beta
        return y_pred

In [229]:
test_model = MyLinearModel(X, y)

In [230]:
test_model.fit()

In [231]:
test_model.beta

array([[0.94954368],
       [2.02452443],
       [1.05601786]])

In [232]:
test_model.std_error

array([0.10773008, 0.09876537, 0.1235912 ])

In [233]:
test_model.rsquared

0.8410063423657346

**(7)** Now we'll go ahead and cheat a little. Use `statsmodels` to fit your model with your toy data to ensure your standard errors and r-squared are correct!

In [234]:
import statsmodels.api as sm

X = sm.add_constant(X)
true_model = sm.OLS(y, X).fit()
true_model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.841
Model:                            OLS   Adj. R-squared:                  0.838
Method:                 Least Squares   F-statistic:                     256.5
Date:                Thu, 30 Nov 2023   Prob (F-statistic):           1.85e-39
Time:                        00:50:19   Log-Likelihood:                -149.20
No. Observations:                 100   AIC:                             304.4
Df Residuals:                      97   BIC:                             312.2
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.9495      0.109      8.681      0.000       0.732       1.167
x1             2.0245      0.100     20.189      0.000       1.825       2.224
x2             1.0560      0.125      8.415      0.000       0.807       1.305
==============================================================================
Omnibus:                        0.820   Durbin-Watson:                   1.919
Prob(Omnibus):                  0.664   Jarque-Bera (JB):                0.732
Skew:                          -0.207   Prob(JB):                        0.694
Kurtosis:                       2.931   Cond. No.                         1.28
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

> Our model matches the statsmodels outputs with some rounding differences since statsmodels cuts off at 3 decimal places.

**(8)** Now implement `predict`! Then test it against your original `X` data -- do you get back something very close to your true `y`?

In [235]:
y_pred = test_model.predict(X_test)
print(
    f"The average difference between our predicted values and our true y values is around {np.mean(y_pred - y):.2f}."
)

The average difference between our predicted values and our true y values is around 0.00.


> Here we can see the average difference between our predicted values and our true y values is close to 0.

**(9)** Finally, create the *option* of fitting the model with or without a constant term. In other words, create an option so that, if the user passes a numpy array *without* a constant term, your code will add a vector of 1s before fitting the model. As in `scikit-learn`, make this an option you set during initialization. 

> We have added a "constant" argument which is default to False and adds a constant term by default. If the user specifies that constant is true (meaning they have already added a constant term), then the initialization will not add a constant term.